name: CI Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: echo "linting..."

      - name: Unit Tests
        run: echo "running tests..."

      - name: Build Docker Image
        run: docker build -t app:${{ github.sha }} .

      - name: Trivy Scan
        run: echo "security scan..."

      - name: Push to ECR
        run: echo "push image"
